In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head(5)

,DATE,TIME,STATUS,NAME,TYPE,SOURCE,PRESENT,TECHNOLOGY,CYCLE_COUNT,VOLTAGE_MIN_DESIGN,VOLTAGE_NOW,CURRENT_NOW,CHARGE_FULL_DESIGN,CHARGE_FULL,CHARGE_NOW,CAPACITY,CAPACITY_LEVEL,MODEL_NAME,MANUFACTURER,SERIAL_NUMBER
0,07/19/23,17:21:30,Active,BAT0,Battery,Charging,1,Li-ion,0,11400000,11575000,1048000,3684000,1873000,92000,4,Critical,DELL-FDRHM08,LGC-LGC3.65,34838.0
1,07/18/23,21:31:41,Suspended,BAT0,Battery,Discharging,1,Li-ion,0,11400000,10623000,1254000,3684000,1920000,96000,5,Critical,DELL-FDRHM08,LGC-LGC3.65,34838.0
2,07/18/23,13:51:45,Active,BAT0,Battery,Discharging,1,Li-ion,0,11400000,11100000,1241000,3684000,1920000,355000,18,Normal,DELL-FDRHM08,LGC-LGC3.65,34838.0
3,07/18/23,13:32:46,Suspended,BAT0,Battery,Discharging,1,Li-ion,0,11400000,10878000,1168000,3684000,1920000,59000,3,Critical,DELL-FDRHM08,LGC-LGC3.65,34838.0
4,07/18/23,13:32:28,Active,BAT0,Battery,Charging,1,Li-ion,0,11400000,11584000,1058000,3684000,1920000,58000,3,Critical,DELL-FDRHM08,LGC-LGC3.65,34838.0

In [41]:
df.dropna(subset=["SERIAL_NUMBER"],inplace=True)

In [42]:
yt = df.drop(columns=["TECHNOLOGY","NAME","TYPE","PRESENT","CYCLE_COUNT","MODEL_NAME","MANUFACTURER","SERIAL_NUMBER","VOLTAGE_MIN_DESIGN","VOLTAGE_NOW","CURRENT_NOW","CHARGE_FULL_DESIGN","CHARGE_FULL","CHARGE_NOW"])

In [43]:
yt.head(5)

       DATE      TIME     STATUS       SOURCE CAPACITY CAPACITY_LEVEL
0  07/19/23  17:21:30     Active     Charging        4       Critical
1  07/18/23  21:31:41  Suspended  Discharging        5       Critical
2  07/18/23  13:51:45     Active  Discharging       18         Normal
3  07/18/23  13:32:46  Suspended  Discharging        3       Critical
4  07/18/23  13:32:28     Active     Charging        3       Critical

In [44]:
yt["DATE"] = pd.to_datetime(df["DATE"],format='%m/%d/%y')

In [45]:
curr_date=yt["DATE"][0]
curr_date=pd.to_datetime(curr_date)

In [46]:
th_bef = curr_date - pd.DateOffset(days=3)
th_bef

Timestamp('2023-07-16 00:00:00')

In [47]:
filtered_yt = yt.loc[(yt["DATE"]>=th_bef) & (yt["DATE"]<=curr_date)]

In [49]:
filtered_yt

         DATE      TIME     STATUS       SOURCE CAPACITY CAPACITY_LEVEL
0  2023-07-19  17:21:30     Active     Charging        4       Critical
1  2023-07-18  21:31:41  Suspended  Discharging        5       Critical
2  2023-07-18  13:51:45     Active  Discharging       18         Normal
3  2023-07-18  13:32:46  Suspended  Discharging        3       Critical
4  2023-07-18  13:32:28     Active     Charging        3       Critical
5  2023-07-18  13:31:44  Suspended  Discharging        2       Critical
6  2023-07-17  11:54:02     Active     Charging        5         Normal
7  2023-07-17  11:52:07  Suspended  Discharging        4       Critical
8  2023-07-17  09:29:32     Active     Charging       49         Normal
9  2023-07-17  08:36:20  Suspended  Discharging       11         Normal
10 2023-07-17  07:13:38     Active  Discharging       59         Normal
11 2023-07-16  21:24:31  Suspended  Discharging       59         Normal
12 2023-07-16  18:32:12     Active     Charging        5         Normal
14 2023-07-16  18:28:24     Active     Charging        2       Critical
15 2023-07-16  18:27:24  Suspended  Discharging        2       Critical
16 2023-07-16  13:22:44     Active     Charging        4       Critical

In [50]:
filtered_yt.to_csv("recent_3_days.csv")